runtime: python311

handlers:
  - url: /.*
    script: auto

env_variables:
  GCP_PROJECT: "poc-yt-cannes-494105"
  GCS_BUCKET: "poc-yt-cannes"
  FIRESTORE_DB: "drivein-poc"
  TASKS_LOCATION: "us-central1"
  VERTEX_LOCATION: "us-central1"
